version: '3'

services:
  application:
    build: ./src
    command: |
      bash -c 'uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:/usr/src/app/
    env_file:
      .env
    expose:
      - 8003
    ports:
      - 8003:8000
    depends_on:
      - database
    networks:
      - network_conf
    links:
      - database:database

  database:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pg-container/pg_init.sh:/docker-entrypoint-initdb.d/pg_init.sh
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - network_conf

networks:
  network_conf:
    driver: bridge